### ISSUE TITLE
“join” subnet seems not working?

### ISSUE THREAD

**Issue by alzhou** [davidc/subnets#5]
When using it with browsers, "join" only displays the subnet length.

**Comment by BlackthornYugen** [comment]
> When using it with browsers, "join" only displays the subnet length.

If you divide a subnet then click the length under the join column it will join them again. It seems to work for me on a mobile browser

**Comment by alzhou** [comment]
> > When using it with browsers, "join" only displays the subnet length.
> 
> 
> 
> If you divide a subnet then click the length under the join column it will join them again. It seems to work for me on a mobile browser

Wow, my mistake. It works indeed. Thanks for pointing it out. I didn't click on the length number because I didn't see any hyperlinks in the Join column.

**Comment by BlackthornYugen** [comment]
I noticed this wasn't closed yet and it might be worth treating this as a UI bug, it's not clear to new users of this tool that the join boxes are actually clickable. 

On the `maskSpanJoinable` class there is supposed to be a `hand` cursor but maybe that got deprecated at some point. It's not on the list of valid cursor properties anymore. 

![image](https://user-images.githubusercontent.com/3138467/116890642-d85c4a00-abfb-11eb-9d46-c2d5d0accfbc.png)ou 

@davidc would you consider a PR that changes the gifs to rotated anchor tags? In addition to making it clear that these are clickable, it might also make it easier for screen readers and things to use your subnet tool. 

Something like this: 

```css
.maskSpan, .maskSpanJoinable {
    background-color: #cccccc;
    text-align: center;
    font-size: x-small;
    font-family: monospace;
    color: black;
}

.maskSpan div {
    transform: rotate(90deg);
}
```

```html
<td rowspan="2" colspan="1" class="maskSpanJoinable">
  <div>
    <a href="#" title="Merge this /17 subnet together">/17</a>
  </div>
</td>
```

Would look like this: 

![image](https://user-images.githubusercontent.com/3138467/116892017-5e2cc500-abfd-11eb-8880-5fab4b3efb49.png)
